spring.application.name=empleados-backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/gestion_empleados}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Tanque.123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true 

server.port=${PORT:8080}

app.jwt.secret=${JWT_SECRET:ZXN0ZS1lcy11bi1zZWNyZXRvLWRlLW1pbi0zMi1jaGFycy1wYXJhLWp3dA==}
app.jwt.expiration-minutes=${JWT_EXP_MIN:480}
app.qr.ttl-seconds=${QR_TTL_SECONDS:45}

app.security.rate-limit.login-max=${RATE_LOGIN_MAX:10}
app.security.rate-limit.scan-max=${RATE_SCAN_MAX:60}
app.security.rate-limit.window-seconds=${RATE_WINDOW_SECONDS:60}

app.attendance.allow-loose-events=${ATTENDANCE_ALLOW_LOOSE_EVENTS:false}
app.attendance.earliest-entry-minutes-before-shift=${ATTENDANCE_EARLY_ENTRY_MINUTES:120}

management.endpoints.web.exposure.include=health,info



app.auth.reset.expiration-minutes=15
app.frontend.reset-password-url=http://localhost:4200/reset-password
app.mail.from=soporte.supersorteo@gmail.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=soporte.supersorteo@gmail.com
#spring.mail.password=yxhf nkmk rsmi vtxl
spring.mail.password=ppgq znbe buaw gtoe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.mail=DEBUG
logging.level.org.eclipse.angus.mail=DEBUG
spring.mail.properties.mail.debug=true
