# =========================
# Produccion (deploy)
# Activar con: --spring.profiles.active=prod
# =========================

server.port=${PORT:8080}

# Railway: puedes definir DB_URL/DB_USER/DB_PASSWORD manualmente,
# o reutilizar variables PGHOST/PGPORT/PGDATABASE/PGUSER/PGPASSWORD del plugin Postgres.
spring.datasource.url=${DB_URL:jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}}
spring.datasource.username=${DB_USER:${PGUSER}}
spring.datasource.password=${DB_PASSWORD:${PGPASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false 
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=${JWT_EXP_MIN:480}

app.qr.ttl-seconds=${QR_TTL_SECONDS:45}
app.security.rate-limit.login-max=${RATE_LOGIN_MAX:10}
app.security.rate-limit.scan-max=${RATE_SCAN_MAX:60}
app.security.rate-limit.window-seconds=${RATE_WINDOW_SECONDS:60}

app.attendance.allow-loose-events=${ATTENDANCE_ALLOW_LOOSE_EVENTS:false}
app.attendance.earliest-entry-minutes-before-shift=${ATTENDANCE_EARLY_ENTRY_MINUTES:120}

app.auth.reset.expiration-minutes=${AUTH_RESET_EXP_MIN:15}
app.frontend.reset-password-url=${FRONTEND_RESET_PASSWORD_URL}
#app.mail.from=${MAIL_FROM}
app.mail.from=soporte.supersorteo@gmail.com

#spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.host=smtp.gmail.com
#spring.mail.port=${MAIL_PORT:587}
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}

spring.mail.port=587
spring.mail.username=soporte.supersorteo@gmail.com
spring.mail.password=ppgq znbe buaw gtoe


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

# CORS de prod (dominios reales separados por coma)
app.security.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

# Logs recomendados en prod
logging.level.root=INFO
logging.level.org.springframework.mail=INFO
logging.level.org.eclipse.angus.mail=INFO
